### ISSUE TITLE
Error handling 404

### ISSUE THREAD

**Issue by quicoto** [nanos/mastodon_get_replies#1]
Just ran this for the first time and it seems one of the URL's failed to load or returned 404, and the action failed.

https://github.com/quicoto/mastodon-get-replies/actions/runs/4353317910/jobs/7607196694

Can we catch these to prevent action failure?

**Comment by nanos** [comment]
Try this one.

You'll just need to update your fork - no further changes needed. Let me know if that works

**Comment by quicoto** [comment]
Seems to work, Thank you for the fast reply!

**Comment by nanos** [comment]
great. thanks for the feedback!
