### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by quicoto** [nanos/mastodon_get_replies#2]
I got another build fail when parsing a URL

Not sure if we can catch these as well, following up on #1 

https://github.com/quicoto/mastodon-get-replies/actions/runs/4362831948/jobs/7628194627

Thank you

**Comment by nanos** [comment]
That error message is almost certainly a red herring: The very fact that it says there was an error, indicates the the error was caught.

As far as I can see this only happened once? I wonder if this was an OOM, or if GitHub killed the job for another reason 🤔

**Comment by quicoto** [comment]
No idea, just wanted to raise this in case was something on our side we could improve.

Feel free to close if not relevant

Thank you for having a look

**Comment by quicoto** [comment]
Another fail, different message I think

https://github.com/quicoto/mastodon-get-replies/actions/runs/4363887432/jobs/7630534273

**Comment by nanos** [comment]
@quicoto Please make sure you are at least on version 2.0.1. Fixed an important bug there.

(I've also re-written the action, so that future versions shouldn't need you to update your fork, as the action now downloads the latest version automatically for every run.)

**Comment by quicoto** [comment]
@nanos Updated to the latest, Thank you !

https://github.com/quicoto/mastodon-get-replies/tree/main
