### ISSUE TITLE
Last step action error

### ISSUE THREAD

**Issue by quicoto** [nanos/mastodon_get_replies#23]
Hello,

I'm getting this error on the last step of the action.

1. https://github.com/quicoto/mastodon-get-replies/actions/runs/4487261467/jobs/7890512058
2. https://github.com/quicoto/mastodon-get-replies/actions/runs/4487339677/jobs/7890665584

Thank you

**Comment by nanos** [comment]
ouch! Will disable this for now, and then try again later.

**Comment by nanos** [comment]
Fixed in v4.1.2
