### ISSUE TITLE
Error getting timeline toots: 'next'

### ISSUE THREAD

**Issue by aeharding** [nanos/mastodon_get_replies#3]
I get the error `Error getting timeline toots: 'next'` many many times for my instance, https://social.harding.dev.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/2166114/223835525-d101e2d9-9b9a-4665-9f55-4845404567d7.png">
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/2166114/223835809-e93ca860-9372-4b18-a2c9-b3e0746eea07.png">

**Comment by aeharding** [comment]
I think it's in an infinite loop, so I'm just gonna cancel it

**Comment by nanos** [comment]
I'm not sure why that would be, but I've put a best-guess fix in, as well as some more error handling and more logging, so at least it shouldn't run an infinite loop anymore.

Can you fetch the latest changes, try again, and let me know the outcome, please?

**Comment by aeharding** [comment]
Hi, thanks, it is no longer infinite-looping.

I think the problem is that my home timeline is empty for the admin user of my Mastodon instance.

As a best practice, my main account on my Mastodon "single-user" instance is not an admin, and the admin of my mastodon instance has no followers/followings.

Is it possible to create an environment variable to configure what timeline for what user to use for scraping?

For example, `TIMELINE_USER=myusername`

It could default to the user that the access token is provided by.

**Comment by nanos** [comment]
> I think the problem is that my home timeline is empty for the admin user of my Mastodon instance.

i thought that would be the reason, but wasn’t sure. Thanks for confirming. 

> Is it possible to create an environment variable to configure what timeline for what user to use for scraping?

Unfortunately I don’t think so. This script is using the [`/api/v1/timelines/home`](https://docs.joinmastodon.org/methods/timelines/#home) endpoint, which doesn’t accept a user ID parameter, but simply returns the home timeline of the authenticated user. 

I’ll have another look if I can find an endpoint that would accept a user ID, but i doubt it.

**Comment by aeharding** [comment]
No problem! You can close this if you want, now that this is cleared up.

**Comment by nanos** [comment]
Yeah, I’ve just had a look, and unfortunately there is no way to get another user's home timeline. Sorry.

**Comment by nanos** [comment]
I don’t know if this is still relevant @aeharding , but I built this today for another purpose:

https://getauth.thms.uk/

you should be able to supply an OAuth token as drop in replacement for the access token. That should then work to pull in replies from the home timeline of any arbitrary user.
