### ISSUE TITLE
Extremely large gaps during rate limit timeout

### ISSUE THREAD

**Issue by p37307** [nanos/mastodon_get_replies#8]
When the API Rate Limit hit is reached for any given toot, it is holding for 6 hours before retrying when running locally. Is that normal? Seems excessive.

**Comment by nanos** [comment]
It’s definitely not normal 😁

the way it works, is that the server where you encounter the rate limit sends back a response saying ‘try again in x minutes’, and the script accepts that. 

There are two possible reasons I can think of here:

1.

**Comment by p37307** [comment]
> It’s definitely not normal

I'm doing a first run and so far I am on my 2nd round of long timeouts.

I'm self-hosted so I am in admin. Also, standard Mastodon install, no bells and whistles or modifications.

>Which time zone is your local machine (that you are running the script on) set to?

Time zone of server is America/Los_Angeles, timezone_offs": -8.

Time zone of my local machine is "timezone": America/New_York "timezone_offset": -5

>And are you able to share a full log / output leading up to this stage?

You want me to copy and paste the terminal output or is there a log somewhere I can fetch?

**Comment by nanos** [comment]
> I'm self-hosted so I am in admin. Also, standard Mastodon install, no bells and whistles or modifications.

normal mastodon behaviour is that the timeout expires after 5 min. 

> You want me to copy and paste the terminal output

yes please. Jus the first ca 20 and the last ca 20 lines are probably enough. 

If you could also let me know the time at which you encountered your issue, that would be great!

**Comment by p37307** [comment]
I made some notes that points to the timeout and other observations. Hope this is what you wanted. :)


[Longbreak during rate limit.txt](https://github.com/nanos/mastodon_get_replies/files/10973687/Longbreak.during.rate.limit.txt)

**Comment by nanos** [comment]
> Waiting to retry at 2023-03-14T20:00:00.243759Z

as of right now that's 1 hour and 12 minutes in the past, no? Am I missing something?

**Comment by nanos** [comment]
Either way, I've updated https://github.com/nanos/mastodon_get_replies/blob/main/get_context.py to provide timestamps with each output line. Can you retry please, and if it happens again, can you provide a similar output again? 

Hopefully that'll shed more light on what's going on.

**Comment by nanos** [comment]
> Right now it is only 16:42:00 UTC

i beg to differ 😉
![1989C1DF-A594-4ABA-B1AB-77FA2BD37404](https://user-images.githubusercontent.com/5182595/225138879-9bb04478-fb4a-4bb0-ac3c-b052edb50df8.jpeg)

either way: please retry with that new log, which should hopefully shed more light on things.

**Comment by p37307** [comment]
Sorry, I meant military time, my local computer time. It was still holding when I shut it down, waiting for 20:00:00 locally. Going to try the new script with the timestamps.

**Comment by p37307** [comment]
At 2023-03-14 18:00:00.103225 Eastern Daylight Time, Rate Limit hit.

_Waiting 14401.853713 sec to retry at 2023-03-14T22:00:00.956938Z_

Looks like this time there is a 4-hour timeout.

Looking at the first log I sent, the first timeout was around 4-hours, then the second one, after little over 300 lines of action, was 6-hours.
[2nd test.txt](https://github.com/nanos/mastodon_get_replies/files/10974347/2nd.test.txt)

**Comment by nanos** [comment]
Hm. Yea, that looks like it’s getting the time zone wrong: 22:00:00 UTC is 18:00:00 EDT, I believe, which means it should’ve waited just 1sec or so. 

I’ll look into this tomorrow morning. 

> after little over 300 lines of action
IIRC the mastodon rate limit is 300 requests per 5 minutes, so that would make sense. .

**Comment by p37307** [comment]
Great. Thanks for support.

**Comment by nanos** [comment]
I've just pushed a new commit, that I hope will fix this.

Since I actually live in UTC, it's hard to test for me though. Can you test, please, and let me know how you get on?

**Comment by p37307** [comment]
Yes, I will run it and get back with you.

**Comment by nanos** [comment]
Amazing. Thanks for the confirmation!
